version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-157-4-216.compute-1.amazonaws.com
            port: '5432'
            database: d280efbo6l87ng
            ssl: true
            user: vpynjnrsrjuysg
            password: 9fa8cd0f7fa17dc28f484b85fbf06dd9514c6987bdc3b5e79d2abca5af22fffb
            migrations: true